[workspace]
members = [
    "crates/jet",
    "crates/jet_runtime",
    "crates/jet_ir",
    "crates/jet_push_macros",
    "crates/jetdbg",
]

resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Tyler Smith"]

[workspace.dependencies]
# External
bnum = "0.14"
clap = { version = "4.6.1", features = ["derive"] }
colored = "3.1.1"
hex = "0.4.3"
inkwell = { version = "0.9.0", features = ["llvm22-1-prefer-dynamic"] }
libc = "0.2.186"
log = "0.4"
paste = "1.0.15"
proc-macro2 = "1.0"
quote = "1.0"
serde = { version = "1.0.228", features = ["derive"] }
sha3 = "0.11.0"
simple_logger = "5.2.0"
syn = { version = "2.0", features = ["full"] }
syntect = "5.3.0"
thiserror = "2.0.18"

# Internal
jet = { path = "crates/jet" }
jet_ir = { path = "crates/jet_ir" }
jet_push_macros = { path = "crates/jet_push_macros" }
jet_runtime = { path = "crates/jet_runtime" }
