[package]
name = "jetdbg"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Debug CLI for compiling and running test EVM contracts with Jet."

[[bin]]
name = "jetdbg"

[dependencies]
clap.workspace = true
inkwell.workspace = true
jet.workspace = true
jet_runtime.workspace = true
log.workspace = true
simple_logger.workspace = true
thiserror.workspace = true
