[package]
name = "jet_runtime"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib", "lib"]

[dependencies]
log = "0.4"
simple_logger = "5.0.0"
inkwell = { git = "https://github.com/TheDan64/inkwell.git", features = ["llvm21-1-prefer-dynamic"] }
sha3 = "0.10.8"
hex = "0.4.3"
colored = "2.1.0"
thiserror = "1.0.61"
jet_ir = { path = "../jet_ir" }

